name: Input injection

on:
  pull_request_target:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
        TEST: ${{ secrets.TEST}}

    steps:
      - name: Check title
        env:
            TITLE: ${{ github.event.pull_request.title }}
        run: |
          title="$TITLE"
          if [[ ! $title =~ ^.*:\ .*$ ]]; then
            echo "Bad issue title"
            exit 1
          fi
