name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.ATALA_GITHUB_TOKEN }}
    
      - name: Test
        run: echo Test