name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          
      - name: Install
        env:
          TEST: ${{ secrets.TEST }}
        run: npm install
